mikrotik:
    resource: "@MikrotikBundle/Controller/"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: MikrotikBundle:Usuario:login }

login_check:
    path: /login_check
logout:
    path: /logout